### PR TITLE
Support for Signature V4

### PR DESCRIPTION
**Pull request by branislav-zahradnik-gdc**
- with possibility to not use it
- with plugin mechanism to use different authentication methods in future

### CODE REVIEW

**Comment by branislav-zahradnik-gdc** [comment]
oops, tested only 01api, 02client is broken :-(

**Comment by ranguard** [comment]
Thanks @branislav-zahradnik-gdc I got the full set of perms tonight, so starting to look into releasing this - give me a few days :)

**Comment by stuartskelton** [comment]
This would be very handy to have released.

**Comment by ranguard** [comment]
Thank you @branislav-zahradnik-gdc released as https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL  - PLEASE test

**Comment by dakkar** [comment]
This is great, and will save me a lot of work. There's only 1 little issue: it will fail when `add_key_filename` is used. In that case, `$request->content` is a coderef that reads the file in chunks, and calling `sha256_hex` on it will not result on a useful hash.

There's a few solutions:

* document this, and let the caller provide their own hash
* change the `PutObject` class to take a filehandle instead / in addition to a coderef, and use the `Digest::SHA::addfile` method
* mark the `_content_sub` as "rewindable" and use it twice (one for the hash, once for the upload), throwing an exception if the `PutObject` class is passed a non-rewindable coderef and no content hash

**Comment by branislav-zahradnik-gdc** [comment]
@dakkar Thanks for testing

I think that [this line](https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Signature/V4.pm#L71) covers problem you mentioned - at least for tests I designed based on our use cases :-)

Can you please provide more info?

**Comment by dakkar** [comment]
Ooh, you're right! I hadn't noticed that bit (and I was doing static analysis in my head).
Also, I had totally failed to notice that the `_content_sub` re-starts the file if it's called after it returns an empty string.
So, yes, this will work. And I'm happy I don't have to do what you just did to make my application work! Thank you!

**Comment by branislav-zahradnik-gdc** [comment]
you are welcome :-)

**Pull request merged**
