### PR TITLE
run 'use_ok' on all modules

### PR DESCRIPTION
**Pull request by yanick**
tweaked the test to `use_ok` all the modules of the distro.

(done as part of the cpan PR challenge)

### CODE REVIEW

**Comment by branislav-zahradnik-gdc** [comment]
good idea, anyway, if you want to test just load modules, please use just require:
```
all_ok (suffix => ..., require => 1)
```
shuffle option will also help

please retain `tests 1 + 1`, it should signal that there are two kinds of tests (in this case one hidden in `Test::Warnings`

**Comment by yanick** [comment]
I added back the `1+1` test plan. I looked at the code of Test::LoadAllModules, however, and it doesn't seem to support a `require` argument. Nor does it shuffle (which I'm not sure of, non-deterministic test runs are hiffy...).

**Comment by branislav-zahradnik-gdc** [comment]
oh, you are right, sorry, my fault, I was looking at `Test::AllModules` :-)

**Comment by yanick** [comment]
Heh, that explains that. :-)

**Comment by branislav-zahradnik-gdc** [comment]
thanks for an idea.
can you please also squash ?

**Comment by yanick** [comment]
Sure!

...

done.

**Pull request merged**
